services:
  traefik:
    container_name: traefik
    image: traefik:2.10.4
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/conf/:/etc/traefik/conf/
      - ./config/certs/:/etc/traefik/certs/
    environment:
      - CF_DNS_API_TOKEN=$CF_DNS_API_TOKEN
    networks:
      - default
      - nas-proxy-external
    restart: unless-stopped
