---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- System:
    - Naspy:
        icon: openmediavault.png
        href: http://192.168.1.23:980
        description: Nas UI Control 
    - Router:
        icon: router.png
        href: http://192.168.1.1
        description: Home router